### PR TITLE
Add linter

### PR DESCRIPTION
**Pull request by alessio**
---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by dongsam** [comment]
Thank you for the PR!  @alessio 

As discussed in https://github.com/cosmos/cosmos-sdk/pull/7032, some of the Lint is broken by keeping the variable names of the PascalCase (`...Id`) automatically generated by the grpc-gateway. Is it okay to exclude these parts from the Lint?

examples
- Error: var `poolId` should be `poolID` (golint)
- Error: method parameter `poolId` should be `poolID` (golint)
- Error: func parameter `swapTypeId` should be `swapTypeID` (golint)
- Error: const `DefaultPoolTypeId` should be `DefaultPoolTypeID` (golint)
- ...

**Comment by alessio** [comment]
> Is it okay to exclude these parts from the Lint?

Of course it is! I'd recommend adding all relevant `//nolint:$LINTER` :+1:

**Comment by hallazzang** [comment]
@alessio I'm currently working on resolving linter issues!

**Comment by alessio** [comment]
Thank you so very much! 🙏🏻

**Pull request merged**
