### PR TITLE
Add DEX Circuit Breaker

### PR DESCRIPTION
**Pull request by kogisin**
## Description

The intention of circuit breaker is to have a contingency plan for a running network which maintains network liveness. This functionality pauses all transaction message types in liquidity module and it can be triggered by only a regulator who has given authority.

closes: #358

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [x] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by zmanian** [comment]
I'm fully on board with the approach here.

**Comment by kogisin** [comment]
@zmanian Thanks for your input!

**Comment by kogisin** [comment]
After a long discussion about the risk of regulation, we decided not to take this approach. Instead, we decided to have this circuit breaker functionality that utilizes Cosmos SDK governance module. We understand that it may be pointless and inefficient since it takes 21 days to pass the proposal but right now we believe that it is the best approach we can think of. We are looking for a way to have another proposal message type in the governance module of Cosmos SDK, which requires lower voting threshold and the proposal triggers instantly when it meets certain threshold to handle this type of cases. Since this logic may be needed in the future, let's leave this PR as is and create another branch to work on it.

**Comment by zmanian** [comment]
I am okay to proceed with or without the circuit breaker in this PR.

**Comment by dongsam** [comment]
https://github.com/tendermint/liquidity/pull/387 is merged, so let me close this PR

**Pull request closed without merging**
